# Generated by Django 4.2.5 on 2023-09-23 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_T', models.FloatField(default=15)),
                ('min_T', models.FloatField(default=14.5, editable=False)),
                ('max_T', models.FloatField(default=15.5, editable=False)),
                ('T_interval', models.FloatField(default=1)),
                ('batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('temprature', models.FloatField()),
                ('fridge', models.BooleanField(default=False)),
                ('warm_element', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('setting', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data_collection.setting')),
            ],
        ),
    ]
