# Generated by Django 4.2.5 on 2023-09-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_batch_t_interval_batch_max_t_batch_min_t_batch_set_t'),
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='setting',
        ),
        migrations.AddField(
            model_name='data',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.batch'),
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
