# Generated by Django 4.2.5 on 2023-09-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_remove_data_setting_data_batch_delete_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='set_temprature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
