# Generated by Django 4.2.5 on 2023-09-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_remove_batch_yeast_batch_yeast'),
        ('data_collection', '0003_data_set_temprature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.batch'),
        ),
    ]
