# Generated by Django 4.2.5 on 2023-09-23 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('orginal_gravity', models.FloatField(blank=True, default=1.03, null=True)),
                ('excepted_gravity', models.FloatField(blank=True, default=1.0, null=True)),
                ('final_gravity', models.FloatField(blank=True, default=None, null=True)),
                ('abv', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag', models.ManyToManyField(blank=True, to='batch.tag')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
