# Generated by Django 4.2.5 on 2023-09-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
