# Generated by Django 4.2.5 on 2023-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='T_interval',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='batch',
            name='max_T',
            field=models.FloatField(default=15.5, editable=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='min_T',
            field=models.FloatField(default=14.5, editable=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='set_T',
            field=models.FloatField(default=15),
        ),
    ]
