# Generated by Django 4.2.5 on 2023-09-23 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_batch_t_interval_batch_max_t_batch_min_t_batch_set_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('set_T', models.FloatField(default=15)),
                ('min_T', models.FloatField(default=14.5, editable=False)),
                ('max_T', models.FloatField(default=15.5, editable=False)),
                ('T_interval', models.FloatField(default=1)),
                ('callibrated_T', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='T_interval',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='max_T',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='min_T',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='set_T',
        ),
        migrations.AddField(
            model_name='batch',
            name='setting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.setting'),
        ),
    ]
