# Generated by Django 4.2.5 on 2023-09-24 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_setting_remove_batch_t_interval_remove_batch_max_t_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_T', models.FloatField(default=20)),
                ('min_T', models.FloatField(default=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='yeast',
            field=models.ManyToManyField(blank=True, null=True, to='batch.yeast'),
        ),
    ]
