# Generated by Django 4.2.5 on 2023-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_yeast_batch_yeast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='yeast',
            field=models.ManyToManyField(blank=True, to='batch.yeast'),
        ),
    ]
