# Generated by Django 4.2.5 on 2023-09-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('batch', '0008_remove_batch_yeast_batch_yeast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
